# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('../..'))
sys.path.append('/Users/jmazoyer/GitProjects/my_projects/Asterix/Asterix/')

# -- Project information -----------------------------------------------------

project = 'Asterix'
copyright = '2021, Johan Mazoyer, Iva Laginja, Axel Potier, Raphaël Galicher'
author = 'Johan Mazoyer, Iva Laginja, Axel Potier, Raphaël Galicher'

# The full version, including alpha/beta/rc tags
# release = 'v2.0'
# release = 'v2.1' # change version 22/02/22
# release = 'v2.2' # change version 15/03/22
# release = 'v2.3' # change version 02/09/22
# release = 'v2.4'  # change version 24/09/22
release = 'v2.5'  # change version 15/12/22


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc', 'sphinx_automodapi.automodapi', 'numpydoc', 'sphinx.ext.coverage', 'sphinx.ext.napoleon',
    "sphinx.ext.graphviz", 'sphinx_rtd_theme', "pyan.sphinx", "sphinx.ext.inheritance_diagram",
]

source_suffix = '.rst'

# The master toctree document.
root_doc = 'index'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

pygments_style = 'sphinx'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

# html_theme = 'alabaster'
html_theme = "sphinx_rtd_theme"


# add graphviz options
graphviz_output_format = "svg"

autodoc_member_order = 'bysource'

autodoc_default_options = {"members": True, "inherited-members": True, "show-inheritance":True}

def patch_automodapi(app):
    """Monkey-patch the automodapi extension to exclude imported members"""
    from sphinx_automodapi import automodsumm
    from sphinx_automodapi.utils import find_mod_objs
    automodsumm.find_mod_objs = lambda *args: find_mod_objs(args[0], onlylocals=True)

def setup(app):
    app.connect("builder-inited", patch_automodapi)