name: Linting

on:
  workflow_dispatch:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
    - master

jobs:
  linter:
    name: Flake8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.13'
    - name: Install flake8
      run: |
        python -m pip install flake8
      shell: bash
    - name: Lint with flake8
      run: flake8 . --max-line-length=121 --count --statistics
      shell: bash